# Law: The future of regulation

## Introduction 

As of now it's quite hard to say what the future of AI/data regulation will be around the world. What is clear is that the world is in a stage of relative infancy with regards to the regulation that does exist. The future can be divided into both the short term view, and the long term view. Much of what is going to occur in the short term is likely inevitable, and can be largely predicted from what currently exists. The long term view will be much more speculative, but also simultaneously much richer in the possibilities for AI/data privacy regulation.


## The problem

AI regulation has a long way to go. It is in a period of infancy, and relative experimentation. The European Union, have passed laws are still figuring out how to optimize the enforcement mechanisms available to them. The United States is relatively early on this process; there has been very little federal activity, and much experimentation on the state level. The federal government has made definitive steps to outline the rights to privacy of individuals, and structuring how those rights can fit into additional regulation. Collectively, this information suggests that there is a strong appetite for additional regulation, and that more will be coming on the way. The industry is learning to adapt to the regulation in a variety of ways. Overall, companies are committed to having a place at the table of regulation. The future is still unclear, and time will only tell how the industry as a whole will respond. 

## The Long Term View

In the long term, regulation will become the norm. It is hard to believe that with the wealth of consumer privacy bills in the pipeline that said regulation is on its way out. For the countries that do not have legislation, any tech company that seeks to do international business will be affected by some sort of regulation,


